steps:
  # 1) Build Docker image from current directory (where Dockerfile & code live)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/advertising-roi-model:latest',
        '.'
      ]

  # 2) Run pytest inside the built image
  - name: 'gcr.io/$PROJECT_ID/advertising-roi-model:latest'
    entrypoint: 'bash'
    args: ['-c', 'pytest -v test_training.py']

  # 3) Push image to registry (only if tests pass)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/advertising-roi-model:latest'
      ]

  # 4) Deploy latest training script to Composer DAGs bucket
  #    (so Airflow/Composer picks up the new version)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        'cp',
        'advertising_model_training.py',
        'gs://us-central1-mlops-airflow-1ed8541c-bucket/dags'
      ]

images:
  - 'gcr.io/$PROJECT_ID/advertising-roi-model:latest'

options:
  logging: CLOUD_LOGGING_ONLY